### PR TITLE
[WIP] Fix null results in recent likes

### PR DESCRIPTION
**Pull request by JakeDawkins**

### CODE REVIEW

**Comment by JakeDawkins** [comment]
@jbaxleyiii idk what the heck that is ^^^^^^, but I think I fixed it 💯. Does this look reasonable?

**Comment by jbaxleyiii** [comment]
@JakeDawkins it does!

**Comment by jbaxleyiii** [comment]
@JakeDawkins cut an alpha?

**Comment by JakeDawkins** [comment]
@jbaxleyiii on it!

**Comment by JakeDawkins** [comment]
@jbaxleyiii queried 200 results with 0 errors :muscle:

**Pull request merged**
