### PR TITLE
197a migration script

### PR DESCRIPTION
**Pull request by Lepozepo**
## How to run:

- Go to `mongoMigrations/v2up.js`
- Modify line 4 to match production
- Run `node v2up.js`

## What does it do?
- It replaces userId's in likes for PrimaryAliasId's
- It moves topics to it's own collection

## What it's missing
- v2down.js to go back down
- A decent library to keep track of migrations

### CODE REVIEW

**Comment by Lepozepo** [comment]
I ran `mongodump` from production and then restored a local DB and ran the migration there. Everything was working.

**Comment by newspringweb** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by IsaacHardy** [comment]
It seems the script only migrates a local mongodb instance. Will something need to be done to migrate alpha/beta/prod?

**Comment by conrad-vanl** [comment]
@IsaacHardy yep! you're correct. Basically this should migrate the data from the old meteor mongo db to the one heighliner uses. We can discuss strategy for how we want to manage this in the meeting today.

**Comment by Lepozepo** [comment]
@IsaacHardy @conrad-vanl this script is definitely bare. Not too sure if we want to have something more robust handling all migrations with a CLI. I think I would be against having a migration script messing with any of the MYSQL and MSSQL databases since those are managed directly by Rock

**Comment by Lepozepo** [comment]
@conrad-vanl this should make the migration less intrusive, let me know if anything else needs to change

**Comment by IsaacHardy** [comment]
@Lepozepo Could we talk about this sometime soon?

**Pull request closed without merging**
