### PR TITLE
137a content likes

### PR DESCRIPTION
**Pull request by Lepozepo**
Fixes [137](https://github.com/NewSpring/Apollos/issues/137)

### CODE REVIEW

**Comment by newspringweb** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Lepozepo** [comment]
This gets the job done but isn't all that efficient (it queries per item). I think I can improve efficiency if I transform IDs and query when it hits the `feed` resolver instead and then pass that down. I'm afraid it'll break a bunch of things though. I'll push for efficiency after the holidays if that's ok.

**Comment by Lepozepo** [comment]
Going through tests right now

newspring

**Review by conrad-vanl — COMMENTED** [review]
Looks good. Understood regarding the performance issue, definitely something we want to keep an eye on, this will not scale at all.

It would probably be more efficient even to do the query with JavaScript - if the user model has an array of content that is liked, to just get the user, and do something is `hasLike = user.likes.find(like => like === content.id)`.

The solution you mentioned is better still.

My only real question on this for now is on the name of the prop `hasLike`. Do you see any existing standard / common practice in the graphql schema for representing boolean props?

`hasLike`
`isLiked`
`liked`

Would probably be good to pick something that is consistent. I know we tend to do `isBool` a lot in the UI components.

**Comment by Lepozepo** [comment]
Yeah, I would definitely prefer not to have the ids pass through memory because that will eventually run out. I think it's easier to scale/increase IO speed on the DB but the indexing we have should be good enough for a pretty long time. I'll definitely have a chance to optimize it after the holidays ^_^

**Comment by Lepozepo** [comment]
Here's a screen of the updated queries
screen shot 2017-12-22 at 9 31 37 am

**Pull request merged**
