### PR TITLE
Person Attribute Mutation

### PR DESCRIPTION
**Pull request by richarddubay**
A mutation to write attribute values to a Person record.

### CODE REVIEW

**Comment by richarddubay** [comment]
@jbaxleyiii This is missing a couple things. First, this just needs a general once over to see if I'm even heading down the right track. I don't often work in Heighliner. Second, I'm not sure where to get the EntityId in order to update the attributes. If you had a minute and wanted to look this over, that would be super helpful!

**Comment by newspringweb** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by jbaxleyiii** [comment]
merged into the other PR. Good start @richarddubay!

**Comment by richarddubay** [comment]
@jbaxleyiii When you're finished, I'd love to see how exactly you did this. 👍

**Pull request closed without merging**
