### PR TITLE
287a profile mutations

### PR DESCRIPTION
**Pull request by Lepozepo**
Required for [this](https://github.com/NewSpring/Apollos/issues/287)

### CODE REVIEW

**Comment by newspringweb** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Lepozepo** [comment]
Update profile:
newspring

Update campus:
newspring2

**Comment by Lepozepo** [comment]
Update home address:
newspring

**Comment by conrad-vanl** [comment]
This _appears_ to disable caching for the current user object? Is that true?

**Comment by Lepozepo** [comment]
@conrad-vanl it does disable caching at the context level (it was already disabled for users), it's optional at the query level. What I'm not certain about is whether it should be disabled at the context level or not. Since all queries use that, a cache seems appropriate but only for the `Id` not for anything else. The issue I was running into with the `currentPerson` query was that it was picking up stale data from the cache after mutations ran. I do believe cache should be opt-in not opt-out in the graphql schema `currentPerson { home { address } }` should always return what's in the DB without requiring the fairly obscure `cache` flag at the `home` level.

**Comment by conrad-vanl** [comment]
@Lepozepo would there be a way perhaps to invalidate the cache in the mutations? Like: https://github.com/NewSpring/Heighliner/blob/master/src/rock/models/people/model.js#L119

**Comment by Lepozepo** [comment]
I can test it out

**Comment by Lepozepo** [comment]
@conrad-vanl those functions specifically target person but none of the resolvers underneath (not sure how long it'll take me to figure out which global IDs to delete). I'll add the cache=false flags to the client instead and revert so we don't lose any speed.

**Comment by conrad-vanl** [comment]
Perfect, thanks @Lepozepo

**Pull request merged**
