### PR TITLE
Ooyala Export Tool -- [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by delianides**
## Ooyala Export Tool

*DO NOT MERGE* 

I would only recommend running this locally. Once Ooyala content has been migrated there's no reason to have an ooyala query on heighliner.

Running:
1. Make sure the ooyala credentials are added to the `.env` file in root.
2. `yarn build && DEBUG=oo yarn start`. The `DEBUG=oo` flag will allow you to see whats happening during the query.

Notes:
- Currently there are over 3200 videos in Ooyala. Pulling data for each one takes time and quite a few API requests. Ooyala's rate limit is 300 per minute. Fortunately the `ooyala-api` will auto-ratelimit for us so we don't have to worry about rerunning the query with different params every time. Make sure you run with the `DEBUG=oo` flag so you can see whats happening. You might see logs with `X-RateLimit-Credits` (How many requests we have left) and `X-RateLimit-Reset` (how many seconds the instance will rest before making the next api request). Keeping this log open will let you know if there are any issues. I've run the full query multiple times and haven't had any issues though so you should be fine.
- The timeout for heighliner is set to 10 minutes. You can see this in the `src/server.js` file. This is to ensure the server doesn't timeout before the query is done. Usually takes between 4-6 minutes to run completely.
- The API requests just for `/v2/assets/` is relatively quick (10-20secs). Those requests are done in 100 asset increments. The `source` and `label` queries add additional time for each query because those are separate API requests. So `backlot` + `source` + `labels` = around 5 minutes. Just `backlot` and `source` is around 3-4 minutes.

Example query:

```gql
query Backlot {
  backlot {
    name
    source
    duration
    createdAt
    duration
    embedCode
    labels {
      name
    }
  }
}
```

You can also clone down the tool [delianides/ooyala-export](https://github.com/delianides/ooyala-export) and simply run `yarn start` to run the above query. The tool will also output a `assets.csv` file in the `ooyala-export` project directory. You can customize the tool based on whatever data would be helpful to import into Wistia.

### CODE REVIEW

**Comment by newspringweb** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>Please assign someone to merge this PR, and optionally include people who should review.</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by IsaacHardy** [comment]
@delianides What are the key names for the ooyala credentials for the `.env` file?

**Comment by IsaacHardy** [comment]
Is it just `OOYALA_KEY=` and `OOYALA_SECRET=`?

**Comment by IsaacHardy** [comment]
@delianides I am not sure where to find those credentials. It is not located here, https://github.com/NewSpring/ops-settings/blob/master/sites/heighliner/env so I am still looking.

**Comment by IsaacHardy** [comment]
@delianides Found the api keys for Wistia and Ooyala. I've attempted to run the script without success. I've receive this error each attempt.
screen shot 2018-02-11 at 3 02 24 pm

**Comment by IsaacHardy** [comment]
@delianides Got it working. Thanks!

**Comment by delianides** [comment]
Sorry I didn't see these until just now.

**Pull request closed without merging**
